---
name: FinallyCanuck.com 
author: Peter Randazzo
url: "pete@randazzo.ca"
description: "I am writing about things that likely only matter to me, because this is my space and not yours."
image: "https://finallycanuck.com/static/img/FinallyCanuck.webp"